version: "3.5"
services:
  backend:
    build: ./backend
    image: sakaar-backend
    env_file:
      - ./.env
    command: bash -c "chmod +x wait_for_databases.sh
             && ./wait_for_databases.sh
             && python manage.py migrate
             && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend:cached
    restart: always
