version: '3.5'
services:
  db:
    env_file:
      - ./.env
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    image: sakaar-backend
    env_file:
      - ./.env
    command: bash -c "python manage.py migrate
             && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 1332:80
    depends_on:
      - backend

volumes:
  postgres-data:
